apiVersion: batch/v1
kind: Job
metadata:
  name: test-linux-binary
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: binary-test
          image: 448265486185.dkr.ecr.us-west-2.amazonaws.com/test:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 1
